### PR TITLE
Don't correct for restitution on normal_vel < 0

### PR DESCRIPTION
**Pull request by johanhelsing**
ref: https://discord.com/channels/691052431525675048/1084206740570124372/1089161165088772146

This check doesn't appear in the paper, but without it, I'm getting issues on object with sharp corners (in my own version of bevy_xpbd).

https://user-images.githubusercontent.com/2620557/227721679-12c3d16f-08ed-4ace-a88a-4c37f3cc09dc.mp4

I think the alternative would be to say that perfectly sharp corners are just not allowed.

### CODE REVIEW

**Comment by Jondolf** [comment]
This could fix that particular problem, but it seems like it causes a ton of explosions and jitteriness (e.g. in the "cubes" example)

**Comment by johanhelsing** [comment]
Ouch, ok... wonder why that is?

**Comment by Jondolf** [comment]
It could be a 3D problem though, as trying a similar example in 2D with squares seems to work better. Though I didn't notice this actually fixing any collision issues in 2D either...

**Comment by johanhelsing** [comment]
Alright, back to the drawing board, i suppose...

**Comment by Aceeri** [comment]
@johanhelsing Are you sure this is a bug? I'd assume rubbing 2 objects would pull the object with it based on friction. Or are we talking about the initial slide not doing anything?

**Comment by johanhelsing** [comment]
Yeah, friction is set to zero here. Direction change comes from restitution.

**Comment by Jondolf** [comment]
I'll close this for being stale and probably outdated.

**Pull request closed without merging**
